services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
      args:
        http_proxy: http://cloudproxy.auiag.corp:8080
        https_proxy: http://cloudproxy.auiag.corp:8080
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - http_proxy=http://cloudproxy.auiag.corp:8080
      - https_proxy=http://cloudproxy.auiag.corp:8080
      - no_proxy=127.0.0.1,localhost,169.254.169.254,customerlabs.com.au,auiag.corp,dataeng.internal,iag.com.au,iagcloud.net,ap-southeast-2.eks.amazonaws.com


  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
      args:
        http_proxy: http://cloudproxy.auiag.corp:8080
        https_proxy: http://cloudproxy.auiag.corp:8080
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - http_proxy=http://cloudproxy.auiag.corp:8080
      - https_proxy=http://cloudproxy.auiag.corp:8080
      - no_proxy=127.0.0.1,localhost,backend,169.254.169.254,customerlabs.com.au,auiag.corp,dataeng.internal,iag.com.au,iagcloud.net,ap-southeast-2.eks.amazonaws.com
